# Generated by Django 4.2.7 on 2025-04-08 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plantaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("hcta_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("variedad", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Proveedores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_empresa", models.CharField(max_length=100)),
                ("nombre_contacto", models.CharField(max_length=100)),
                ("telefono_contacto", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="SuperAdministrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("apellidos", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="Activo",
                        max_length=10,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="superadministrador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Maestros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("apellidos", models.CharField(blank=True, max_length=255, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "telefono_contacto",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="Activo",
                        max_length=10,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("insumo", "Insumo"), ("herrero", "Herrero")],
                        default="Herrero",
                        max_length=10,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maestros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Insumos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("capacidad", models.FloatField()),
                ("precio", models.IntegerField()),
                ("carencia", models.IntegerField()),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores",
                        to="core.proveedores",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Huerto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("hcta_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "plantaciones",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.plantaciones",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("apellidos", models.CharField(blank=True, max_length=255, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "telefono_contacto",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="Activo",
                        max_length=10,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventarioInsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "huerto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.huerto"
                    ),
                ),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.insumos"
                    ),
                ),
            ],
            options={
                "unique_together": {("huerto", "insumo")},
            },
        ),
    ]
