# Generated by Django 4.2.7 on 2025-04-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(choices=[('fertilizante', 'Fertilizante'), ('herbicida', 'Herbicida'), ('fungicida', 'Fungicida'), ('insecticida', 'Insecticida'), ('otro', 'Otro')], default='Fertilizante', max_length=20),
        ),
    ]
