# Generated by Django 4.2.7 on 2025-04-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_huerto_plantaciones"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantaciones",
            name="nombre",
        ),
    ]
