# Generated by Django 4.2.7 on 2025-04-08 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_remove_plantaciones_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plantacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variedad", models.CharField(max_length=255)),
                ("hcta_total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name="Insumos",
            new_name="Insumo",
        ),
        migrations.RenameModel(
            old_name="Maestros",
            new_name="Maestro",
        ),
        migrations.RenameModel(
            old_name="Proveedores",
            new_name="Proveedor",
        ),
        migrations.RemoveField(
            model_name="huerto",
            name="plantaciones",
        ),
        migrations.DeleteModel(
            name="Plantaciones",
        ),
        migrations.AddField(
            model_name="plantacion",
            name="huerto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plantaciones",
                to="core.huerto",
            ),
        ),
    ]
