# Generated by Django 4.2.7 on 2025-04-18 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_insumo_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedoresIn', to='core.proveedor'),
        ),
    ]
