# Generated by Django 4.2.7 on 2025-04-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_insumo_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='codigo',
        ),
    ]
