# Generated by Django 4.2.7 on 2025-04-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_plantacion_rename_insumos_insumo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="huerto",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
