# Generated by Django 4.2.7 on 2025-04-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_huerto_ubicacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="huerto",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
