# Generated by Django 4.2.7 on 2025-04-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_insumoherreria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumoherreria',
            name='estado',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('inoperativo', 'Inoperativo')], default='Operativo', max_length=11),
        ),
    ]
