# Generated by Django 4.2.7 on 2025-04-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_huerto_ubicacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="huerto",
            name="nombre_ubicacion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
